env:
  global:
    - CC_TEST_REPORTER_ID=cad1c314cf184342a171855fd619376a4197c4e91fecb1bb3ebbe10286430779

language: node_js
node_js:
  - "8"

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

install:
  - yarn

script:
  - jest --coverage

after_script:
  - ./cc-test-reporter after-build -t lcov
